project_id = "ysmwlknwwbdmghlxwumb"

[functions.ai-search]
verify_jwt = true

[functions.ai-document-processor]  
verify_jwt = true

[functions.folder-operations]
verify_jwt = true

[functions.storage-management]
verify_jwt = true

[functions.document-operations]
verify_jwt = true

[functions.extract-document-content]
verify_jwt = true