// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ysmwlknwwbdmghlxwumb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzbXdsa253d2JkbWdobHh3dW1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzOTA3MDAsImV4cCI6MjA3Mzk2NjcwMH0.ckTOonkv5mfLVxc44kkDnIWrv5TjKxy3UkHlLJkcMCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});